kind: Pod
apiVersion: v1
metadata:
  name: storage-pod
spec:
  containers:
  - name: storage-pod
    image: ubuntu:18.04
    command: ["/bin/sh", "-c", "tail -f /dev/null"]
    volumeMounts:
      - name: csi-volume
        mountPath: /data 
  volumes:
  - name: csi-volume
    persistentVolumeClaim:
      claimName: storage-pvc
